import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronDown, ContactRound, Heart, LoaderCircle, Plus, Search, Sparkles, Trash2, UserRound } from "lucide-react";
import { mailClient } from "./data/client";
import { openUrl } from "@tauri-apps/plugin-opener";
import type { ContactFieldSuggestion, ContactProfile, ContactTimelineItem, SaveContactRequest } from "./domain";
import { readAiFeatures, readAiRequestConfig } from "./aiSettings";
import { errorMessage } from "./errors";

const empty = (): SaveContactRequest => ({ id:null,displayName:"",role:"",company:"",location:"",bio:"",notes:"",links:[],photoData:null,favorite:false,addresses:[] });
const photoUrl = (value:string|null) => value ? `data:image/jpeg;base64,${value}` : null;
async function encodePhoto(file:File):Promise<string>{
  const bitmap=await createImageBitmap(file); const scale=Math.min(1,160/Math.max(bitmap.width,bitmap.height));
  const canvas=document.createElement("canvas"); canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));
  const context=canvas.getContext("2d"); if(!context)throw new Error("Could not read the selected photo"); context.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
  let quality=.82;let data=canvas.toDataURL("image/jpeg",quality).split(",")[1]??"";
  while(data.length>87_000&&quality>.35){quality-=.1;data=canvas.toDataURL("image/jpeg",quality).split(",")[1]??"";}
  if(data.length>87_000)throw new Error("Photo is too large to save after resizing"); return data;
}

export function ContactsWorkspace({onOpenThread,initialContactId=null}:{onOpenThread(id:string):void;initialContactId?:string|null}){
  const [query,setQuery]=useState("");const [profiles,setProfiles]=useState<ContactProfile[]>([]);const [selectedId,setSelectedId]=useState<string|null>(null);const [profile,setProfile]=useState<ContactProfile|null>(null);
  const [timeline,setTimeline]=useState<ContactTimelineItem[]>([]);const [timelineHasMore,setTimelineHasMore]=useState(false);const [draft,setDraft]=useState<SaveContactRequest>(empty());const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);const [adding,setAdding]=useState(false);const [confirmDelete,setConfirmDelete]=useState(false);const [suggestions,setSuggestions]=useState<ContactFieldSuggestion[]>([]);const [enriching,setEnriching]=useState(false);
  const searchRef=useRef<HTMLInputElement>(null);
  const requestedContactId=useRef(initialContactId);
  const preserveSuggestionsForId=useRef<string|null>(null);
  const aiEnabled=readAiFeatures().contactEnrichment;
  const load=useCallback(async(keepProfile?:ContactProfile)=>{setLoading(true);setError(null);try{let result=await mailClient.listContactProfiles(query,500);const requestedId=requestedContactId.current;if(requestedId&&!query.trim()){requestedContactId.current=null;if(!result.some(item=>item.id===requestedId)){const requestedProfile=await mailClient.getContactProfile(requestedId);if(requestedProfile)result=[requestedProfile,...result];}}if(keepProfile&&!result.some(item=>item.id===keepProfile.id)&&!query.trim())result=[keepProfile,...result];setProfiles(result);setSelectedId(current=>keepProfile?.id??(current&&result.some(item=>item.id===current)?current:requestedId&&result.some(item=>item.id===requestedId)?requestedId:result[0]?.id??null));}catch(reason){setError(errorMessage(reason));}finally{setLoading(false);}},[query]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),120);return()=>clearTimeout(timer);},[load]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(event.key!=="/"||event.metaKey||event.ctrlKey||event.altKey)return;const target=event.target;if(target instanceof HTMLElement&&(target.isContentEditable||["INPUT","TEXTAREA","SELECT"].includes(target.tagName)))return;event.preventDefault();searchRef.current?.focus();};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey);},[]);
  useEffect(()=>{if(!selectedId){setProfile(null);setTimeline([]);setTimelineHasMore(false);if(!adding)setDraft(empty());return;}const preserveSuggestions=preserveSuggestionsForId.current===selectedId;preserveSuggestionsForId.current=null;let active=true;void Promise.all([mailClient.getContactProfile(selectedId),mailClient.contactTimeline(selectedId,0,20)]).then(([item,events])=>{if(!active)return;setProfile(item);setTimeline(events);setTimelineHasMore(events.length===20);setDraft(item?{id:item.id,displayName:item.displayName??"",role:item.role??"",company:item.company??"",location:item.location??"",bio:item.bio??"",notes:item.notes??"",links:item.links,photoData:item.photoData,favorite:item.favorite,addresses:item.addresses}:empty());setAdding(false);if(!preserveSuggestions)setSuggestions([]);}).catch(reason=>{if(active)setError(errorMessage(reason));});return()=>{active=false;};},[selectedId]);
  const setField=(field:keyof SaveContactRequest,value:unknown)=>setDraft(current=>({...current,[field]:value}));
  const save=async()=>{setBusy(true);setError(null);try{const saved=await mailClient.saveContactProfile({...draft,addresses:draft.addresses.map(value=>value.trim()).filter(Boolean),links:draft.links.map(value=>value.trim()).filter(Boolean)});setProfile(saved);setDraft({...saved});setSelectedId(saved.id);setAdding(false);await load(saved);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}};
  const startNew=()=>{setSelectedId(null);setProfile(null);setDraft(empty());setAdding(true);setConfirmDelete(false);setSuggestions([]);};
  const deleteProfile=async()=>{if(!profile||profile.id.startsWith("derived:"))return;if(!confirmDelete){setConfirmDelete(true);return;}try{await mailClient.deleteContactProfile(profile.id);setConfirmDelete(false);setSelectedId(null);setProfile(null);setAdding(false);await load();}catch(reason){setError(errorMessage(reason));}};
  const enrich=async()=>{if(!selectedId)return;setEnriching(true);setError(null);try{const config=readAiRequestConfig("enhancing a contact");const results=await mailClient.enrichContact(selectedId,config.provider,config.model,config.endpoint);setSuggestions(results);if(!results.length)setError("No supported profile details were found in the available emails.");}catch(reason){setError(errorMessage(reason));}finally{setEnriching(false);}};
  const applySuggestion=async(item:ContactFieldSuggestion)=>{const next={...draft};if(item.field==="link")next.links=[...new Set([...next.links,item.value])];else next[item.field]=item.value;setDraft(next);setBusy(true);try{const saved=await mailClient.saveContactProfile({...next,id:profile?.id??selectedId});setProfile(saved);setDraft({...saved});setSuggestions(current=>current.filter(value=>value!==item));if(saved.id!==selectedId)preserveSuggestionsForId.current=saved.id;setSelectedId(saved.id);await load(saved);}catch(reason){setError(errorMessage(reason));}finally{setBusy(false);}};
  const loadOlder=async()=>{if(!selectedId)return;try{const next=await mailClient.contactTimeline(selectedId,timeline.length,20);setTimeline(current=>[...current,...next]);setTimelineHasMore(next.length===20);}catch(reason){setError(errorMessage(reason));}};
  const avatar=photoUrl(draft.photoData);const initial=(draft.displayName||draft.addresses[0]||"?").trim().slice(0,1).toLocaleUpperCase();
  const linksText=useMemo(()=>draft.links.join("\n"),[draft.links]);
  const orderedProfiles=useMemo(()=>[...profiles].sort((a,b)=>Number(b.favorite)-Number(a.favorite)||Date.parse(b.lastInteractedAt??"")-Date.parse(a.lastInteractedAt??"")||(a.displayName||a.addresses[0]||"").localeCompare(b.displayName||b.addresses[0]||"",undefined,{sensitivity:"base"})),[profiles]);
  const favoriteProfiles=orderedProfiles.filter(item=>item.favorite);const recentProfiles=orderedProfiles.filter(item=>!item.favorite);
  return <section className="contacts-workspace" aria-label="Contacts">
    <header className="contacts-header"><div><span className="eyebrow">Address book</span><h1>Contacts</h1></div><button type="button" className="contact-primary-button" onClick={startNew}><Plus size={16}/>New contact</button></header>
    <div className="contacts-workspace-body">
      <aside className="contacts-list-panel" aria-label="Contact list"><label className="contacts-search"><Search size={16}/><input ref={searchRef} aria-label="Search contacts" placeholder="Search contacts" value={query} onChange={event=>setQuery(event.target.value)}/><kbd>/</kbd></label><p className="contacts-sort-hint">Favorites first · then recent activity</p>
        {loading?<p className="contacts-status">Loading contacts…</p>:null}{error?<p className="contacts-error" role="alert">{error}</p>:null}
        <div className="contacts-list">{favoriteProfiles.length?<section className="contact-list-group" aria-label="Favorites"><h2>Favorites</h2>{favoriteProfiles.map(item=><ContactListItem key={item.id} item={item} selected={selectedId===item.id&&!adding} onSelect={()=>{setAdding(false);setSelectedId(item.id);}}/>)}</section>:null}{recentProfiles.length?<section className="contact-list-group" aria-label="Recent contacts"><h2>Recent</h2>{recentProfiles.map(item=><ContactListItem key={item.id} item={item} selected={selectedId===item.id&&!adding} onSelect={()=>{setAdding(false);setSelectedId(item.id);}}/>)}</section>:null}</div>
        {!loading&&profiles.length===0?<p className="contacts-empty">No contacts found. People you email will appear here.</p>:null}
      </aside>
      <section className="contact-profile-panel" aria-label="Contact details">
        {adding||profile?<>
          <div className="contact-profile-top"><div className="contact-identity"><label className="contact-avatar large" title="Contact photo">{avatar?<img src={avatar} alt=""/>:<span>{initial||<UserRound/>}</span>}<input type="file" accept="image/avif,image/gif,image/jpeg,image/png,image/webp" aria-label="Upload contact photo" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{setField("photoData",await encodePhoto(file));}catch(reason){setError(errorMessage(reason));}}}/></label><div><input className="contact-name-input" aria-label="Name" placeholder="Name" value={draft.displayName??""} onChange={event=>setField("displayName",event.target.value)}/><input aria-label="Role" placeholder="Role or title" value={draft.role??""} onChange={event=>setField("role",event.target.value)}/></div></div>
            <div className="contact-profile-actions"><button type="button" aria-label="Favorite contact" aria-pressed={draft.favorite} onClick={()=>setField("favorite",!draft.favorite)}><Heart size={17} fill={draft.favorite?"currentColor":"none"}/></button>{profile&&!profile.id.startsWith("derived:")?<button type="button" aria-label="Delete contact" onClick={()=>void deleteProfile()}><Trash2 size={17}/></button>:null}</div></div>
          <div className="contact-editor-grid"><label>Emails<textarea aria-label="Email addresses" rows={Math.max(1,draft.addresses.length)} placeholder="name@example.com" value={draft.addresses.join("\n")} onChange={event=>setField("addresses",event.target.value.split(/[\n,]+/).map(value=>value.trim()).filter(Boolean))}/></label><label>Company<input value={draft.company??""} onChange={event=>setField("company",event.target.value)}/></label><label>Location<input value={draft.location??""} onChange={event=>setField("location",event.target.value)}/></label><label>Links<textarea rows={2} value={linksText} onChange={event=>setField("links",event.target.value.split("\n").map(value=>value.trim()).filter(Boolean))}/></label><label className="wide">About<textarea rows={3} value={draft.bio??""} onChange={event=>setField("bio",event.target.value)}/></label><label className="wide">Notes<textarea rows={4} value={draft.notes??""} onChange={event=>setField("notes",event.target.value)}/></label></div>
          {profile?.links.length?<nav className="contact-links" aria-label="Contact links">{profile.links.map(link=><button key={link} type="button" onClick={()=>void openUrl(link)}>{new URL(link).hostname} <span>{link}</span></button>)}</nav>:null}
          <div className="contact-save-row"><span>{profile?`${profile.sentCount} sent · ${profile.receivedCount} received`:"New profile"}</span><div>{confirmDelete?<><span>Delete this profile?</span><button type="button" onClick={()=>void deleteProfile()}>Confirm</button><button type="button" onClick={()=>setConfirmDelete(false)}>Cancel</button></>:null}<button type="button" className="contact-primary-button" disabled={busy} onClick={()=>void save()}><Check size={15}/>Save contact</button></div></div>
          {aiEnabled&&profile?<section className="contact-enrichment"><header><div><Sparkles size={16}/><strong>AI suggestions</strong></div><button type="button" disabled={enriching} onClick={()=>void enrich()}>{enriching?<LoaderCircle className="spin" size={14}/>:null}Enhance with AI</button></header>{suggestions.map((item,index)=><article key={`${item.field}-${index}`}><div><span>{item.field}</span><strong>{item.value}</strong><blockquote>{item.excerpt}</blockquote><button type="button" className="contact-suggestion-source" onClick={()=>onOpenThread(item.sourceThreadId)}>View source email</button></div><button type="button" onClick={()=>void applySuggestion(item)}>Use suggestion</button></article>)}</section>:null}
          {timeline.length?<section className="contact-timeline"><h2>Recent emails</h2>{timeline.map(item=><button type="button" key={item.threadId} onClick={()=>onOpenThread(item.threadId)}><span><strong>{item.subject||"(no subject)"}</strong><small>{item.accountId} · {new Date(item.sentAt).toLocaleDateString()}</small></span><ChevronDown size={14}/></button>)}{timelineHasMore?<button type="button" className="contact-load-more" onClick={()=>void loadOlder()}>Load older emails</button>:null}</section>:null}
        </>:<div className="contacts-empty-state"><ContactRound size={30}/><p>Select a contact to see their details</p></div>}
      </section>
    </div>
  </section>;
}

function ContactListItem({item,selected,onSelect}:{item:ContactProfile;selected:boolean;onSelect():void}){
  const avatar=photoUrl(item.photoData);
  return <button type="button" className={`contact-list-item${selected?" selected":""}`} aria-pressed={selected} onClick={onSelect}>
    <span className="contact-avatar small">{avatar?<img src={avatar} alt=""/>:<span>{(item.displayName||item.addresses[0]||"?").slice(0,1).toLocaleUpperCase()}</span>}</span><span className="contact-list-copy"><strong>{item.displayName||item.addresses[0]}</strong><small>{item.company||item.addresses[0]}</small></span>{item.favorite?<Heart size={14} fill="currentColor"/>:null}
  </button>;
}
